### ISSUE TITLE
weird ass error

### ISSUE THREAD

**Issue by Hellscaped** [siefkenj/react-userscripts#21]
So I'm writing a userscript for a roblox clone I'm a moderator for, and my script has no problem building, it says this and doesnt run when I go to the site.
Uncaught SyntaxError: missing ] after element list
[home:1:143](https://www.syntax.eco/home)note: [ opened at line 1, column 96[home:1:96](https://www.syntax.eco/home)
injected: env: missing script "9b0175d4-c0ae-43fc-96d0-698281dbe6f4"!

**Comment by thrailkillr** [comment]
it turns out that I did my @grants wrong in the header, there was nothing wrong with my code except that.
