### ISSUE TITLE
Can't load `http://localhost:8124/react-userscripts.user.js` because of host web's following Content Security Policy

### ISSUE THREAD

**Issue by vkboo** [siefkenj/react-userscripts#27]
<img width="931" alt="image" src="https://github.com/user-attachments/assets/46bd73d4-e15a-4249-abae-ed7526dae8d7">
<img width="1915" alt="image" src="https://github.com/user-attachments/assets/6b5f2d05-759c-472e-a240-41ebca1496ec">

**Comment by siefkenj** [comment]
Hmmm. Does it work in Firefox under Greasemonkey?

You might also try changing `@grant none` to something more permissive.

**Comment by vkboo** [comment]
> Hmmm. Does it work in Firefox under Greasemonkey?
> 
> You might also try changing `@grant none` to something more permissive.

1. It works normally in Firefox;
2. However, in Chrome, there are still CSP-related errors. I'm not sure if this issue can be resolved within this library regarding security.

**Comment by siefkenj** [comment]
Yeah. Hopefully it works in production mode. You might be constrained to doing dev on Firefox.

**Comment by vkboo** [comment]
production mode is fine. Thank you.
