### ISSUE TITLE
TailwindCSS

### ISSUE THREAD

**Issue by glatzl** [siefkenj/react-userscripts#6]
Hi, 

Is it possible to use Tailwind CSS?
https://tailwindcss.com/docs/guides/create-react-app

**Comment by siefkenj** [comment]
Maybe. Give it a try! The important modification to `cra` is to prevent bundling and prevent script hashes from being appended to file names.

See https://github.com/siefkenj/react-userscripts/blob/master/userscript/config-overrides.js for where this is done using `react-app-rewired`.

**Comment by glatzl** [comment]
Thanks for quick response! Amazing to be able to use React for userscripts.
I found this guide on how to setup Tailwind without Craco, and it works
https://pomelozone.hashnode.dev/add-tailwind-jit-to-a-react-app-without-ejecting-or-using-craco

**Comment by siefkenj** [comment]
That's great! Would you like to add some information to the README for others who want to do this?

**Comment by glatzl** [comment]
When I'm done with build and 100% sure everything is working I'll add some info
